//
//  PlayerDict.swift
//  NBA Player Compare
//
//  Created by Harrison Shu on 7/11/22.
//

import Foundation

struct PlayerDict {
    let dict: Dictionary<String,Int> = [
        "Alex Abrines": 1,
        "Quincy Acy": 2,
        "Jordan Adams": 3,
        "Steven Adams": 4,
        "Aaron Affalo": 5,
        "Alexis Ajinca": 6,
        "Cole Aldrich": 7,
        "LaMarcus Aldrich": 8,
        "Cliff Alexander": 9,
        "Lavoy Allen": 10,
        "Tony Allen": 11,
        "Al-Farouq Aminu":12,
        "Lou Amundson": 13,
        "Chris Andersen": 14,
        "Alan Anderson": 15,
        "James Anderson": 16,
        "Justin Anderson": 17,
        "Kyle Anderson": 18,
        "Ryan Anderson": 19,
        "Giannis AntetoKounmpo": 20,
        "Carmelo Anthony": 21,
        "Joel Anthony": 22,
        "Trevor Ariza": 23,
        "Egegan Arna": 24,
        "Darrell Arthur": 25,
        "Netanel Artzi": 26,
        "Omer Asik": 27,
        "D.J. Augustin": 28,
        "Jeff Ayres": 29,
        "Luke Babbitt": 30,
        "Cameron Bairstow": 31,
        "Ron Baker": 32,
        "Wade Baldin IV": 33,
        "Leandro Barbosa": 34,
        "J.J. Barea": 35,
        "Harrison Barnes": 36,
        "Matt Barnes": 37,
        "Will Barton": 38,
        "Brandon Bass": 39,
        "Nicolas Batum": 40,
        "Jerryd Bayless": 41,
        "Aron Baynes": 42,
        "Ercan Bayrak": 43,
        "Kent Bazemore": 44,
        "Bradley Beal": 45,
        "Malik Beasley": 46,
        "Michael Beasley": 47,
        "Marco Belinelli": 48,
        "DeAndre Bembry": 49,
        "Dragan Bender": 50,
        "Anthony Bennett": 51,
        "Davis Bertans": 52,
        "Patrick Beverly": 53,
        "Bismack Biyombo": 54,
        "Nemanja Bjelica": 55,
        "Tarik Black": 56,
        "Steve Blake": 57,
        "Oz Blayzer": 58,
        "Eric Bledsoe": 59,
        "Bojan Bogdanovic": 60,
        "Andrew Bogut": 61,
        "Joel Bolomboy": 62,
        "Matt Bonner": 63,
        "Devin Booker": 64,
        "Trevor Booker": 65,
        "Paulinho Boracino": 66,
        "Chris Bosh": 67,
        "Avery Bradley": 68,
        "Elton Brand": 69,
        "Corey Brewer": 70,
        "Malcolm Brogdon": 71,
        "Aaron Brooks": 72,
        "Anthony Brown": 73,
        "Bobby Brown": 74,
        "Jaylen Brown": 75,
        "Lorenzo Brown": 76,
        "Markel Brown": 77,
        "Nicolas Brussino": 78,
        "Kobe Bryant": 79,
        "Reggie Buckner": 80,
        "Chase Budinger": 81,
        "Reggie Bullock": 82,
        "Trey Burke": 83,
        "Alec Burks": 84,
        "Caron Butler": 85,
        "Jimmy Butler": 86,
        "Bruno Caboclo": 87,
        "Jose Calderon": 88,
        "Kentavious Caldwell-Pope": 89,
        "Mathias Calfani": 90,
        "Isasiah Canaan": 91,
        "Clint Capela": 92,
        "DeMarre Carroll": 93,
        "Vince Carter": 94,
        "Michael Carter-Williams": 95,
        "Omri Casspi": 96,
        "Willie Cauley-Stein": 97,
        "Amir Celestin": 98,
        "Bruno Cerella": 99,
        "Leandro Cerminato": 100
        ]
        
        }
        
    


